# k8s/helm/environments/prod/values.yaml
image:
  repository: eslintpurity/weather-app
  tag: prod-helms
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
ingress:
  enabled: true
  hostname: prod-helm-weather-local