steps:
  # Build the application
  - name: node:20
    entrypoint: npm
    args: ['ci']
    
  - name: node:20
    entrypoint: npm
    args: ['run', 'build']

  # Build Docker image
  - name: gcr.io/cloud-builders/docker
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/my-nodejs-app-repo/nodejs-app:$COMMIT_SHA',
      '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/my-nodejs-app-repo/nodejs-app:latest',
      '.'
    ]

  # Push Docker images
  - name: gcr.io/cloud-builders/docker
    args: [
      'push',
      '${_REGION}-docker.pkg.dev/$PROJECT_ID/my-nodejs-app-repo/nodejs-app:$COMMIT_SHA'
    ]
    
  - name: gcr.io/cloud-builders/docker
    args: [
      'push',
      '${_REGION}-docker.pkg.dev/$PROJECT_ID/my-nodejs-app-repo/nodejs-app:latest'
    ]

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: us-central1  # Default, overridden by --substitutions flag