# weather-app-helms/environment/staging/values.yaml
image:
  repository: eslintpurity/weather-app
  tag: staging-helms  # This gets overwritten automatically
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
ingress:
  enabled: true
  hostname: staging.helm.weather.local