apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-blue
  namespace: app
  labels:
    app: weather-app
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-app
      version: blue
  template:
    metadata:
      labels:
        app: weather-app
        version: blue
    spec:
      containers:
        - name: weather-app
          image: weather-app:good
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10

