apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-canary
  namespace: app
  labels:
    app: weather-app
    version: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-app
      version: canary
  template:
    metadata:
      labels:
        app: weather-app
        version: canary
    spec:
      containers:
        - name: weather-app
          image: weather-app:local
          ports:
            - containerPort: 5000
