apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-canary
  namespace: app
  labels:
    app: weather-app
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-app
      version: green
  template:
    metadata:
      labels:
        app: weather-app
        version: green
    spec:
      containers:
        - name: weather-app
          image: weather-app:local
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /  
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
