apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: weather-local-cert
  namespace: default
spec:
  secretName: weather-local-tls
  commonName: weather.local
  dnsNames:
    - weather.local
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  duration: 8760h  # 1 year
  renewBefore: 360h
