apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-app-helms
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: weather-app=weather-app
    argocd-image-updater.argoproj.io/weather-app.update-strategy: latest
spec:
  project: default
  source:
    repoURL: https://github.com/doyinhubx/weather-runner.git
    targetRevision: main
    path: weather-app-helms
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: helms
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
