# k8s/argocd-apps/weather-app-helm-prod.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-app-helm-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/doyinhubx/weather-runner.git
    targetRevision: main
    path: weather-app-helms
    helm:
      valueFiles:
        - environments/prod/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-helm
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
