# weather-app-helms/environment/dev/values.yaml
image:
  repository: eslintpurity/weather-app
  tag: dev-helms  # This gets overwritten automatically
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
ingress:
  enabled: true
  hostname: dev.helm.weather.local