name: Branch Check Demo

on:
  push:
    branches:
      - '*'     # run on all branches

jobs:
  validate-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Branch Pattern Check
        uses: doyinhubx/check-branch-action@v1
        with:
          pattern: '^feature/'