name: Clean Old Docker Hub Images

on:
  schedule:
    - cron: '0 4 * * *' # Runs daily at 4:00 AM UTC
  workflow_dispatch:   # Allows manual trigger

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository
      - name: Checkout Repo
        uses: actions/checkout@v4

      # 2. Log in to Docker Hub
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. List Docker Hub images
      - name: List Docker Hub Images
        run: |
          echo "Listing images in ${DOCKERHUB_USERNAME}/${DOCKERHUB_REPO}..."
          curl -s -u ${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }} \
            "https://hub.docker.com/v2/repositories/${DOCKERHUB_USERNAME}/${DOCKERHUB_REPO}/tags?page_size=100" \
            | jq -r '.results[] | "\(.name) \(.last_updated)"'

      # 4. Delete old images (example: keep last 5 images)
      - name: Delete old images
        run: |
          echo "Deleting older images while keeping last 5..."
          IMAGES=$(curl -s -u ${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }} \
            "https://hub.docker.com/v2/repositories/${DOCKERHUB_USERNAME}/${DOCKERHUB_REPO}/tags?page_size=100" \
            | jq -r '.results | sort_by(.last_updated) | .[:-5] | .[].name')
          for tag in $IMAGES; do
            echo "Deleting tag: $tag"
            curl -X DELETE -s -u ${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }} \
              "https://hub.docker.com/v2/repositories/${DOCKERHUB_USERNAME}/${DOCKERHUB_REPO}/tags/$tag/"
          done