name: Build & Push Docker Image

on:
  push:
    branches: [main, dev, staging]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REGISTRY: docker.io
      IMAGE_NAME: eslintpurity/weather-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag from branch
        id: set_tag
        run: |
          BRANCH=$(echo "${GITHUB_REF#refs/heads/}")
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          echo "tag=${BRANCH}-helms" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t $REGISTRY/${{ env.IMAGE_NAME }}:${{ steps.set_tag.outputs.tag }} .

      - name: Push Docker image
        run: |
          docker push $REGISTRY/${{ env.IMAGE_NAME }}:${{ steps.set_tag.outputs.tag }}
