name: Build and Deploy to Kubernetes via Helms and ArgoCD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Image Tag (short SHA with helm suffix)
        id: vars
        run: echo "tag=eslintpurity/weather-app:${GITHUB_SHA::7}-helm" >> $GITHUB_OUTPUT

      - name: Build & Push Docker Image
        run: |
          docker build -t ${{ steps.vars.outputs.tag }} .
          docker push ${{ steps.vars.outputs.tag }}

      - name: Update Helm values.yaml with new image tag
        run: |
          sed -i "s|tag:.*|tag: ${GITHUB_SHA::7}-helm|" weather-app-helms/values.yaml

      - name: Commit and Push Updated Helm values.yaml
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
        run: |
          git config user.name "$GIT_USER_NAME"
          git config user.email "$GIT_USER_EMAIL"
          git add weather-app-helms/values.yaml
          git commit -m "ci: update image tag to ${{ steps.vars.outputs.tag }}"
          git push https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:main
