name: Simulate ArgoCD Image Updater

on:
  push:
    branches: [main]

jobs:
  image-updater-simulation:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout Repo
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Install kubectl, kind, and Helm
      - name: Install Kubernetes tools
        run: |
          curl -sLo kubectl https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
          chmod +x kubectl && sudo mv kubectl /usr/local/bin/
          curl -sLo kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x kind && sudo mv kind /usr/local/bin/
          curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      # 4. Create a temporary Kind cluster
      - name: Create Kind cluster
        run: |
          kind create cluster --name argocd-cluster

      # 5. Start a local Docker registry for Image Updater to watch
      - name: Start Local Registry
        run: |
          # Start registry container if not already running
          docker run -d --restart=always --name registry -p 5000:5000 registry:2 || true

          # Connect registry to kind network
          docker network connect kind registry || true

          # Make sure /etc/hosts inside runner resolves "registry" -> 127.0.0.1
          echo "127.0.0.1 registry" | sudo tee -a /etc/hosts

          # Verify registry is reachable
          curl -s http://registry:5000/v2/_catalog || echo "Registry not yet ready"

      # 6. Install ArgoCD
      - name: Install ArgoCD
        run: |
          kubectl create namespace argocd
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
          kubectl wait --for=condition=available --timeout=120s deployment/argocd-server -n argocd

      # 7. Install ArgoCD Image Updater
      - name: Install ArgoCD Image Updater
        run: |
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/master/manifests/install.yaml
          kubectl wait --for=condition=available --timeout=120s deployment/argocd-image-updater -n argocd

      # 8. Build and push initial (1.0.0) image to local registry
      - name: Build Initial Image
        run: |
          docker build -t registry:5000/weather-app:1.0.0 -f Dockerfile.good .
          docker push registry:5000/weather-app:1.0.0

      # 9. Create helms namespace
      - name: Create helms namespace
        run: kubectl create namespace helms || true

      # 10. Deploy Helm Release (ensures Deployment exists)
      - name: Deploy Helm Release
        run: |
          helm upgrade --install weather-app-helms ./weather-app-helms \
            --namespace helms \
            --set image.repository=registry:5000/weather-app \
            --set image.tag=1.0.0 \
            --set image.pullPolicy=IfNotPresent

      # 11. Apply ArgoCD Application with Image Updater annotations
      - name: Deploy ArgoCD Application
        run: |
          kubectl apply -f - <<'EOF'
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: weather-app-helms
            namespace: argocd
            annotations:
              argocd-image-updater.argoproj.io/image-list: weather-app=registry:5000/weather-app
              argocd-image-updater.argoproj.io/weather-app.update-strategy: latest
              argocd-image-updater.argoproj.io/weather-app.helm.image-name: image.repository
              argocd-image-updater.argoproj.io/weather-app.helm.image-tag: image.tag
          spec:
            project: default
            source:
              repoURL: https://github.com/doyinhubx/weather-runner.git
              targetRevision: main
              path: weather-app-helms
              helm:
                values: |
                  image:
                    repository: registry:5000/weather-app
                    tag: "1.0.0"
                    pullPolicy: IfNotPresent
            destination:
              server: https://kubernetes.default.svc
              namespace: helms
            syncPolicy:
              automated:
                selfHeal: true
                prune: true
          EOF

      # 12. Build and push newer (2.0.0) image to local registry
      - name: Build Newer Image
        run: |
          docker build -t registry:5000/weather-app:2.0.0 -f Dockerfile.good .
          docker push registry:5000/weather-app:2.0.0

      # 13. Wait for Image Updater to detect new tag
      - name: Wait for ArgoCD Image Updater
        run: |
          echo "⏳ Waiting up to 120s for Image Updater to update the Application..."
          for i in {1..12}; do
            FINAL_IMAGE=$(kubectl get deployment weather-app-helms -n helms -o jsonpath="{.spec.template.spec.containers[0].image}" 2>/dev/null || echo "")
            echo "Current image: $FINAL_IMAGE"
            if [[ "$FINAL_IMAGE" == *":2.0.0" ]]; then
              echo "✅ Image Updater successfully updated to 2.0.0!"
              exit 0
            fi
            sleep 10
          done
          echo "❌ Image Updater did not update to 2.0.0 in time"
          exit 1

      # 14. Final pod status
      - name: Final Pod Status
        run: kubectl get pods -n helms -o wide
